//
// Last.Backend LLC CONFIDENTIAL
// __________________
//
// [2014] - [2017] Last.Backend LLC
// All Rights Reserved.
//
// NOTICE:  All information contained herein is, and remains
// the property of Last.Backend LLC and its suppliers,
// if any.  The intellectual and technical concepts contained
// herein are proprietary to Last.Backend LLC
// and its suppliers and may be covered by Russian Federation and Foreign Patents,
// patents in process, and are protected by trade secret or copyright law.
// Dissemination of this information or reproduction of this material
// is strictly forbidden unless prior written permission is obtained
// from Last.Backend LLC.
//

export const APP_LIST_FETCH_REQUEST = 'APP_LIST_FETCH_REQUEST';
export const APP_LIST_FETCH_SUCCESS = 'APP_LIST_FETCH_SUCCESS';
export const APP_LIST_FETCH_FAILURE = 'APP_LIST_FETCH_FAILURE';

export const APP_FETCH_REQUEST = 'APP_FETCH_REQUEST';
export const APP_FETCH_SUCCESS = 'APP_FETCH_SUCCESS';
export const APP_FETCH_FAILURE = 'APP_FETCH_FAILURE';
export const APP_CREATE_REQUEST = 'APP_CREATE_REQUEST';
export const APP_CREATE_SUCCESS = 'APP_CREATE_SUCCESS';
export const APP_CREATE_FAILURE = 'APP_CREATE_FAILURE';
export const APP_CREATE_CLEAR = 'APP_CREATE_CLEAR';
export const APP_UPDATE_REQUEST = 'APP_UPDATE_REQUEST';
export const APP_UPDATE_SUCCESS = 'APP_UPDATE_SUCCESS';
export const APP_UPDATE_FAILURE = 'APP_UPDATE_FAILURE';
export const APP_UPDATE_CLEAR = 'APP_UPDATE_CLEAR';
export const APP_REMOVE_REQUEST = 'APP_REMOVE_REQUEST';
export const APP_REMOVE_SUCCESS = 'APP_REMOVE_SUCCESS';
export const APP_REMOVE_FAILURE = 'APP_REMOVE_FAILURE';

export const SERVICE_LIST_FETCH_REQUEST = 'SERVICE_LIST_FETCH_REQUEST';
export const SERVICE_LIST_FETCH_SUCCESS = 'SERVICE_LIST_FETCH_SUCCESS';
export const SERVICE_LIST_FETCH_FAILURE = 'SERVICE_LIST_FETCH_FAILURE';

export const SERVICE_FETCH_REQUEST  = 'SERVICE_FETCH_REQUEST';
export const SERVICE_FETCH_SUCCESS  = 'SERVICE_FETCH_SUCCESS';
export const SERVICE_FETCH_FAILURE  = 'SERVICE_FETCH_FAILURE';
export const SERVICE_CREATE_REQUEST = 'SERVICE_CREATE_REQUEST';
export const SERVICE_CREATE_SUCCESS = 'SERVICE_CREATE_SUCCESS';
export const SERVICE_CREATE_FAILURE = 'SERVICE_CREATE_FAILURE';
export const SERVICE_UPDATE_REQUEST = 'SERVICE_UPDATE_REQUEST';
export const SERVICE_UPDATE_SUCCESS = 'SERVICE_UPDATE_SUCCESS';
export const SERVICE_UPDATE_FAILURE = 'SERVICE_UPDATE_FAILURE';
export const SERVICE_REMOVE_REQUEST = 'SERVICE_REMOVE_REQUEST';
export const SERVICE_REMOVE_SUCCESS = 'SERVICE_REMOVE_SUCCESS';
export const SERVICE_REMOVE_FAILURE = 'SERVICE_REMOVE_FAILURE';

export const SERVICE_SPEC_CREATE_REQUEST = 'SERVICE_SPEC_REMOVE_REQUEST';
export const SERVICE_SPEC_CREATE_SUCCESS = 'SERVICE_SPEC_REMOVE_SUCCESS';
export const SERVICE_SPEC_CREATE_FAILURE = 'SERVICE_SPEC_REMOVE_FAILURE';
export const SERVICE_SPEC_UPDATE_REQUEST = 'SERVICE_SPEC_UPDATE_REQUEST';
export const SERVICE_SPEC_UPDATE_SUCCESS = 'SERVICE_SPEC_UPDATE_SUCCESS';
export const SERVICE_SPEC_UPDATE_FAILURE = 'SERVICE_SPEC_UPDATE_FAILURE';
export const SERVICE_SPEC_REMOVE_REQUEST = 'SERVICE_SPEC_REMOVE_REQUEST';
export const SERVICE_SPEC_REMOVE_SUCCESS = 'SERVICE_SPEC_REMOVE_SUCCESS';
export const SERVICE_SPEC_REMOVE_FAILURE = 'SERVICE_SPEC_REMOVE_FAILURE';

export const TEMPLATE_LIST_FETCH_REQUEST = 'TEMPLATE_LIST_FETCH_REQUEST';
export const TEMPLATE_LIST_FETCH_SUCCESS = 'TEMPLATE_LIST_FETCH_SUCCESS';
export const TEMPLATE_LIST_FETCH_FAILURE = 'TEMPLATE_LIST_FETCH_FAILURE';

export const SOCKET_OPEN = 'SOCKET_OPEN';
export const SOCKET_CLOSE = 'SOCKET_CLOSE'; 

export const CLUSTER_LIST_FETCH_REQUEST = 'CLUSTER_LIST_FETCH_REQUEST';
export const CLUSTER_LIST_FETCH_SUCCESS = 'CLUSTER_LIST_FETCH_SUCCESS';
export const CLUSTER_LIST_FETCH_FAILURE = 'CLUSTER_LIST_FETCH_FAILURE';

export const CLUSTER_FETCH_REQUEST = 'CLUSTER_LIST_REQUEST';
export const CLUSTER_FETCH_SUCCESS = 'CLUSTER_LIST_SUCCESS';
export const CLUSTER_FETCH_FAILURE = 'CLUSTER_LIST_FAILURE';
export const CLUSTER_UPDATE_REQUEST = 'CLUSTER_UPDATE_REQUEST';
export const CLUSTER_UPDATE_SUCCESS = 'CLUSTER_UPDATE_SUCCESS';
export const CLUSTER_UPDATE_FAILURE = 'CLUSTER_UPDATE_FAILURE';
export const CLUSTER_REMOVE_REQUEST = 'CLUSTER_REMOVE_REQUEST';
export const CLUSTER_REMOVE_SUCCESS = 'CLUSTER_REMOVE_SUCCESS';
export const CLUSTER_REMOVE_FAILURE = 'CLUSTER_REMOVE_FAILURE';
export const CLUSTER_CREATE_REQUEST = 'CLUSTER_CREATE_REQUEST';
export const CLUSTER_CREATE_SUCCESS = 'CLUSTER_CREATE_SUCCESS';
export const CLUSTER_CREATE_FAILURE = 'CLUSTER_CREATE_FAILURE';

export const NODE_LIST_FETCH_REQUEST = 'NODE_LIST_FETCH_REQUEST';
export const NODE_LIST_FETCH_SUCCESS = 'NODE_LIST_FETCH_SUCCESS';
export const NODE_LIST_FETCH_FAILURE = 'NODE_LIST_FETCH_FAILURE';

export const NODE_FETCH_REQUEST = 'NODE_LIST_REQUEST';
export const NODE_FETCH_SUCCESS = 'NODE_LIST_SUCCESS';
export const NODE_FETCH_FAILURE = 'NODE_LIST_FAILURE';
export const NODE_REMOVE_REQUEST = 'NODE_REMOVE_REQUEST';
export const NODE_REMOVE_SUCCESS = 'NODE_REMOVE_SUCCESS';
export const NODE_REMOVE_FAILURE = 'NODE_REMOVE_FAILURE';
export const NODE_CREATE_REQUEST = 'NODE_CREATE_REQUEST';
export const NODE_CREATE_SUCCESS = 'NODE_CREATE_SUCCESS';
export const NODE_CREATE_FAILURE = 'NODE_CREATE_FAILURE';

export const REPO_LIST_FETCH_REQUEST = 'REPO_LIST_FETCH_REQUEST';
export const REPO_LIST_FETCH_SUCCESS = 'REPO_LIST_FETCH_SUCCESS';
export const REPO_LIST_FETCH_FAILURE = 'REPO_LIST_FETCH_FAILURE';

export const REPO_FETCH_REQUEST = 'REPO_FETCH_REQUEST';
export const REPO_FETCH_SUCCESS = 'REPO_FETCH_SUCCESS';
export const REPO_FETCH_FAILURE = 'REPO_FETCH_FAILURE';
export const REPO_REMOVE_REQUEST = 'REPO_REMOVE_REQUEST';
export const REPO_REMOVE_SUCCESS = 'REPO_REMOVE_SUCCESS';
export const REPO_REMOVE_FAILURE = 'REPO_REMOVE_FAILURE';
export const REPO_CREATE_REQUEST = 'REPO_REMOVE_REQUEST';
export const REPO_CREATE_SUCCESS = 'REPO_REMOVE_SUCCESS';
export const REPO_CREATE_FAILURE = 'REPO_REMOVE_FAILURE';
export const REPO_CREATE_CLEAR = 'REPO_CREATE_CLEAR';

export const REPO_BUILD_UPDATE_SUCCESS = 'REPO_BUILD_UPDATE_SUCCESS';
export const REPO_BUILD_UPDATE_FAILURE = 'REPO_BUILD_UPDATE_FAILURE';
export const REPO_BUILD_UPDATE_REQUEST = 'REPO_BUILD_UPDATE_REQUEST';

export const REPO_DEPLOY_TEMPLATE_CREATE_REQUEST = 'REPO_DEPLOY_TEMPLATE_CREATE_REQUEST';
export const REPO_DEPLOY_TEMPLATE_CREATE_SUCCESS = 'REPO_DEPLOY_TEMPLATE_CREATE_SUCCESS';
export const REPO_DEPLOY_TEMPLATE_CREATE_FAILURE = 'REPO_DEPLOY_TEMPLATE_CREATE_FAILURE';
export const REPO_DEPLOY_TEMPLATE_FETCH_REQUEST = 'REPO_DEPLOY_TEMPLATE_FETCH_REQUEST';
export const REPO_DEPLOY_TEMPLATE_FETCH_SUCCESS = 'REPO_DEPLOY_TEMPLATE_FETCH_SUCCESS';
export const REPO_DEPLOY_TEMPLATE_FETCH_FAILURE = 'REPO_DEPLOY_TEMPLATE_FETCH_FAILURE';
export const REPO_DEPLOY_TEMPLATE_LIST_FETCH_REQUEST = 'REPO_DEPLOY_TEMPLATE_LIST_FETCH_REQUEST';
export const REPO_DEPLOY_TEMPLATE_LIST_FETCH_SUCCESS = 'REPO_DEPLOY_TEMPLATE_LIST_FETCH_SUCCESS';
export const REPO_DEPLOY_TEMPLATE_LIST_FETCH_FAILURE = 'REPO_DEPLOY_TEMPLATE_LIST_FETCH_FAILURE';
export const REPO_DEPLOY_TEMPLATE_UPDATE_REQUEST = 'REPO_DEPLOY_TEMPLATE_UPDATE_REQUEST';
export const REPO_DEPLOY_TEMPLATE_UPDATE_SUCCESS = 'REPO_DEPLOY_TEMPLATE_UPDATE_SUCCESS';
export const REPO_DEPLOY_TEMPLATE_UPDATE_FAILURE = 'REPO_DEPLOY_TEMPLATE_UPDATE_FAILURE';
export const REPO_DEPLOY_TEMPLATE_REMOVE_REQUEST = 'REPO_DEPLOY_TEMPLATE_REMOVE_REQUEST';
export const REPO_DEPLOY_TEMPLATE_REMOVE_SUCCESS = 'REPO_DEPLOY_TEMPLATE_REMOVE_SUCCESS';
export const REPO_DEPLOY_TEMPLATE_REMOVE_FAILURE = 'REPO_DEPLOY_TEMPLATE_REMOVE_FAILURE';
export const REPO_DEPLOY_TEMPLATE_SET_DEFAULT_REQUEST = 'REPO_DEPLOY_TEMPLATE_SET_DEFAULT_REQUEST';
export const REPO_DEPLOY_TEMPLATE_SET_DEFAULT_SUCCESS = 'REPO_DEPLOY_TEMPLATE_SET_DEFAULT_SUCCESS';
export const REPO_DEPLOY_TEMPLATE_SET_DEFAULT_FAILURE = 'REPO_DEPLOY_TEMPLATE_SET_DEFAULT_FAILURE';

export const BUILD_LIST_FETCH_REQUEST = 'BUILD_LIST_FETCH_REQUEST';
export const BUILD_LIST_FETCH_SUCCESS = 'BUILD_LIST_FETCH_SUCCESS';
export const BUILD_LIST_FETCH_FAILURE = 'BUILD_LIST_FETCH_FAILURE';

export const BUILD_FETCH_REQUEST  = 'BUILD_FETCH_REQUEST';
export const BUILD_FETCH_SUCCESS  = 'BUILD_FETCH_SUCCESS';
export const BUILD_FETCH_FAILURE  = 'BUILD_FETCH_FAILURE';
export const BUILD_CREATE_REQUEST = 'BUILD_CREATE_REQUEST';
export const BUILD_CREATE_SUCCESS = 'BUILD_CREATE_SUCCESS';
export const BUILD_CREATE_FAILURE = 'BUILD_CREATE_FAILURE';

export const REGISTRY_REPO_LIST_FETCH_REQUEST = 'REGISTRY_REPO_LIST_FETCH_REQUEST';
export const REGISTRY_REPO_LIST_FETCH_SUCCESS = 'REGISTRY_REPO_LIST_FETCH_SUCCESS';
export const REGISTRY_REPO_LIST_FETCH_FAILURE = 'REGISTRY_REPO_LIST_FETCH_FAILURE';
export const REGISTRY_TAG_LIST_FETCH_REQUEST = 'REGISTRY_TAG_LIST_FETCH_REQUEST';
export const REGISTRY_TAG_LIST_FETCH_SUCCESS = 'REGISTRY_TAG_LIST_FETCH_SUCCESS';
export const REGISTRY_TAG_LIST_FETCH_FAILURE = 'REGISTRY_TAG_LIST_FETCH_FAILURE';